// Generated by https://quicktype.io

class PopularModel {
  bool? adult;
  String? backdropPath;
  List<int>? genreIds;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  PopularModel({
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });
  factory PopularModel.fromMap(Map<String, dynamic> movie) {
    return PopularModel(
      id: movie['id'],
      backdropPath: movie['backdrop_path'],
      posterPath: movie['poster_path'],
      originalLanguage: movie['original_language'],
      overview: movie['overview'],
      popularity: movie['popularity'],
      releaseDate: movie['release_date'],
      title: movie['title'],
      voteAverage: movie['vote_average'],
      voteCount: movie['vote_count'],
    );
  }
}

class Cast {
  String? knownForDepartment;
  String? originalName;
  String? profilePath;
  String? character;

  Cast({
    this.knownForDepartment,
    this.originalName,
    this.profilePath,
    this.character,
  });
  factory Cast.fromMap(Map<String, dynamic> cast) {
    return Cast(
        knownForDepartment: cast['known_for_department'],
        originalName: cast['original_name'],
        profilePath: cast['profile_path'],
        character: cast['character']);
  }
}
