// Generated by https://quicktype.io

class PopularModel {
  bool? adult;
  String? backdropPath;
  List<int>? genreIds;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;
  List<VideoResult>? videos;

  PopularModel({
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
    this.videos,
  });
  factory PopularModel.fromMap(Map<String, dynamic> movie) {
    return PopularModel(
      id: movie['id'],
      backdropPath: movie['backdrop_path'],
      posterPath: movie['poster_path'],
      originalLanguage: movie['original_language'],
      overview: movie['overview'],
      popularity: movie['popularity'],
      releaseDate: movie['release_date'],
      title: movie['title'],
      voteAverage: movie['vote_average'],
      voteCount: movie['vote_count'],
      videos: movie['videos'] != null
          ? List<VideoResult>.from(
              movie['videos']['results']
                  .map((video) => VideoResult.fromMap(video)),
            )
          : null,
    );
  }
}

class VideoResult {
  String? id;
  String? iso6391;
  String? iso31661;
  String? key; // Esta es la clave del video de YouTube
  String? name;
  String? site;
  int? size;
  String? type;

  VideoResult({
    this.id,
    this.iso6391,
    this.iso31661,
    this.key,
    this.name,
    this.site,
    this.size,
    this.type,
  });

  factory VideoResult.fromMap(Map<String, dynamic> json) {
    return VideoResult(
      id: json['id'],
      iso6391: json['iso_639_1'],
      iso31661: json['iso_3166_1'],
      key: json['key'],
      name: json['name'],
      site: json['site'],
      size: json['size'],
      type: json['type'],
    );
  }
}

class Cast {
  String? knownForDepartment;
  String? originalName;
  String? profilePath;
  String? character;

  Cast({
    this.knownForDepartment,
    this.originalName,
    this.profilePath,
    this.character,
  });
  factory Cast.fromMap(Map<String, dynamic> cast) {
    return Cast(
        knownForDepartment: cast['known_for_department'],
        originalName: cast['original_name'],
        profilePath: cast['profile_path'],
        character: cast['character']);
  }
}
